
--DROP EVENT SESSION [Track_CDC_Usage] ON SERVER 
--GO

CREATE EVENT SESSION [Track_CDC_Usage]
ON SERVER
    ADD EVENT sqlserver.cdc_session
    ADD TARGET package0.event_file
    (SET FILENAME = N'C:\XE_Logs\CDCTracking.xel', max_file_size = (50), MAX_ROLLOVER_FILES = (5))
WITH
(
    MAX_MEMORY = 4096KB,
    EVENT_RETENTION_MODE = ALLOW_SINGLE_EVENT_LOSS,
    MAX_DISPATCH_LATENCY = 5 SECONDS,
    MAX_EVENT_SIZE = 0KB,
    MEMORY_PARTITION_MODE = NONE,
    TRACK_CAUSALITY = OFF,
    STARTUP_STATE = OFF
);
GO


